### ISSUE TITLE
How to make a new gva module

### ISSUE THREAD

**Issue by vtimofeev01** [dlstreamer/dlstreamer#167] opened 2020-12-12 09:43 UTC
can U add an example to make a cpp code as new separate gva module but not postproc (like gvaidentify before)
Thank U

**Comment by nnshah1** [comment] 2020-12-12 16:42
@vtimofeev01 So we understand more clearly: are you asking for an example like gvaidentify (that is to add back the gvaidentify sample?) - Or are you asking for a sample that has a different set of functionality from gvaidentify? If the latter, what features need to be demonstrated?

**Comment by vtimofeev01** [comment] 2020-12-12 21:14
I mean how to made my own module and to put in into the docker file. A separate gva module (not a postproc like in cpp example). I am not looking for  gvaidentify functionality.

**Comment by mliu2020** [comment] 2020-12-21 19:27
@vtimofeev01,

Do you mean a new gva element? If you want to development a GStreamer element, it must be inserted into the GST command line and has its own proprieties.

If you want to go this path, you have to do a lot of development and maintenance works.

Mark

**Comment by vtimofeev01** [comment] 2020-12-26 09:21
Thank U
What will be the right way? Is the way of gvaidentify right?

**Comment by mliu2020** [comment] 2021-01-14 08:01
Hi @vtimofeev01,

Sorry for the long time delay.

From our conversation, it is to me that you asking about general development approach. If I understand correctly, you should follow general GStreamer elements creation guideline, for example: https://gstreamer.freedesktop.org/documentation/application-development/basics/elements.html?gi-language=c#creating-a-gstelement.

About docker, there are 2 options:

- You can build our image and then create your own dockerfile and use our image as base:
`
FROM dl_streamer:latest
…
`
- You can use one of openVINO’s public images as base: https://hub.docker.com/u/openvino, then add whatever you need to this dockerfile.

Let me know if this answers your question.

Mark Liu

**Comment by mliu2020** [comment] 2021-02-16 00:06
@vtimofeev01,

Sorry for being delay to answer your question.

If my understanding is correct, you are asking to create your own inference element and add it to a docker file. Then you should clone the whole source tree and make sure it works, then you can add it to Docker file. 

If this is correct, I can help you to set it up.

If you are not working on this project, could I close this issue?

Mark Liu

**Comment by vtimofeev01** [comment] 2021-02-17 22:14
Hi!

Yes! it is correct

**Comment by mliu2020** [comment] 2021-02-21 06:30
@vtimofeev01,

To show how to add an inference element to the library, we not only need a sample code, a build and debug process is also required.

I think a document could solve this problem, so let me try it.

Mark Liu

**Comment by intel-neena** [comment] 2021-03-22 23:31
@vtimofeev01 gvaidentify shows the right way of creating a gva element. You can find it [here](https://github.com/openvinotoolkit/dlstreamer_gst/tree/v1.0/samples/gst_launch/reidentification). Is this sufficient for you?

**Comment by vtimofeev01** [comment] 2021-04-10 18:50
Hello!!!!
the compile was failed

```
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gstreamer-1.0>=1.14'
--   Found gstreamer-1.0, version 1.16.2
-- Checking for module 'gstreamer-video-1.0>=1.14'
--   Found gstreamer-video-1.0, version 1.16.2
-- Found OpenCV: /opt/intel/openvino_2021.3.394/opencv (found version "4.5.2") found components: core imgproc 
CMake Error at CMakeLists.txt:26 (set_target_lib_version):
  Unknown CMake command "set_target_lib_version".


-- Configuring incomplete, errors occurred!
```


End of LOG file is

```
  collapse library dir [/opt/intel/openvino_2021/data_processing/dl_streamer/lib/../lib] ==> [/opt/intel/openvino_2021/data_processing/dl_streamer/lib]
  collapse library dir [/opt/intel/openvino_2021/data_processing/gstreamer/lib/../lib] ==> [/opt/intel/openvino_2021/data_processing/gstreamer/lib]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/7] ==> [/usr/lib/gcc/x86_64-linux-gnu/7]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib] ==> [/usr/lib]
  collapse library dir [/lib/x86_64-linux-gnu] ==> [/lib/x86_64-linux-gnu]
  collapse library dir [/lib/../lib] ==> [/lib]
  collapse library dir [/usr/lib/x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
  collapse library dir [/usr/lib/../lib] ==> [/usr/lib]
  collapse library dir [/opt/intel/openvino_2021/data_processing/dl_streamer/lib] ==> [/opt/intel/openvino_2021/data_processing/dl_streamer/lib]
  collapse library dir [/opt/intel/openvino_2021/data_processing/gstreamer/lib] ==> [/opt/intel/openvino_2021/data_processing/gstreamer/lib]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/7/../../..] ==> [/usr/lib]
  implicit libs: [stdc++;m;gcc_s;gcc;c;gcc_s;gcc]
  implicit dirs: [/opt/intel/openvino_2021/data_processing/dl_streamer/lib;/opt/intel/openvino_2021/data_processing/gstreamer/lib;/usr/lib/gcc/x86_64-linux-gnu/7;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib]
  implicit fwks: []

```

**Comment by mliu2020** [comment] 2021-04-12 23:20
Hi @vtimofeev01,

This looks like a different issue, could you submit a new issue and create a full command line of the build command?

Your current description and log doesn't show which binary you are try to build.

Mark

**Comment by vtimofeev01** [comment] 2021-04-13 00:09
Hello!

This one
```
cd gvaidentify
cmake .
make
```

from [here](https://github.com/openvinotoolkit/dlstreamer_gst/tree/v1.0/samples/gst_launch/reidentification)

**Comment by mliu2020** [comment] 2021-05-01 02:20
Hi @vtimofeev01 
Sorry for delayed response,
I am confused with your reply, I can't figure out your reply after @intel-neena's post, could you have a clear description to your problem and what the question is?

Mark

**Comment by vtimofeev01** [comment] 2021-05-01 14:42
Hello @mliu2020 !

u try to cmake gvaidentufy but I get an fault   `Unknown CMake command "set_target_lib_version".`
please tell me how to build this example

Thank U

**Comment by mliu2020** [comment] 2021-05-03 22:20
@vtimofeev01 

Sure, I want to reproduce your issue and help you. Since I didn't build this before, could you give me your steps, were you building host or docker?

Mark

**Comment by akwrobel** [comment] 2023-03-28 18:04
Closed due to age and no submitter responce.

**Closed by akwrobel** 2023-03-28 18:04 UTC
Labels: document enhancement
